version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
    allow:
      # mypy updates bring new checks.
      - dependency-name: "mypy"
      # want to test on latest dependencies
      - dependency-name: "trio"
      - dependency-name: "trio-websocket"
      - dependency-name: "attrs"
      - dependency-name: "cattrs"
      - dependency-name: "httpx"
