[tool.poetry]
name = "bloom"
version = "0.1.0"
description = "a compact library for discord."
authors = ["A5rocks <git@helvetica.moe>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
trio = "^0.18.0"
trio-websocket = "^0.9.2"
attrs = "^21.2.0"

[tool.poetry.dev-dependencies]
# docs
Sphinx = "^3.5.2"
furo = "^2021.4.11-beta.34"
sphinx-autobuild = "^2021.3.14"
sphinxcontrib-trio = "^1.1.2"

# dev
mypy = "^0.812"
isort = "^5.8.0"
flake8 = "^3.9.2"
pylint = "^2.8.3"

# stubs
trio-typing = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
