[build-system]
# TODO: use poetry
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "bloom"
author = "A5rocks"
author-email = "git@helvetica.moe"
home-page = "https://github.com/A5rocks/bloom"
classifiers = [ "License :: OSI Approved :: Apache Software License",]
requires-python = ">=3.7,<3.10"
dist-name = "discord-bloom"
description-file = "README.md"

# make sure to keep this up to date with requirements.txt
requires = [
	"trio ~= 0.18.0",
	"trio-websocket ~= 0.9.2",
	"attrs ~= 21.2.0"
]

[tool.flit.metadata.requires-extra]
doc = ["sphinx", "furo", "sphinx-autobuild", "sphinxcontrib-trio", ]
dev = [
# tools
	"mypy",
	"isort",
	"flake8",
	"pylint",
# types
	"trio-typing ~= 0.5.0",
]
