name: lint

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" 

jobs:
  lints:
    strategy:
      fail-fast: false
      matrix:
        min_deps: [true, false]

    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"

      - run: pip install -U pip wheel

      - name: install tomli and tomli-w
        if: matrix.min_deps
        run: pip install tomli tomli-w

      - name: update pyproject.toml to pin minimum dependencies
        if: matrix.min_deps
        run: python scripts/min_deps.py && cat pyproject.toml

      - name: install dependencies
        run: pip install .[dev]

      - name: run mypy
        run: mypy bloom/
      
      - name: run isort
        run: isort -c bloom/

      - name: run flake8
        run: flake8 bloom/

      - name: run black
        run: black bloom/ --diff --check
