name: lint

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" 

jobs:
  lints:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"

      - run: pip install -U pip wheel

      - name: install dependencies
        run: pip install .[dev]

      - name: run mypy
        if: always()
        run: mypy bloom/
      
      - name: run isort
        if: always()
        run: isort -c bloom/

      - name: run flake8
        if: always()
        run: flake8 bloom/

      - name: run black
        if: always()
        run: black bloom/ --diff --check
